### ISSUE TITLE
Persistent mode with config watching

### ISSUE THREAD

**Issue by AndreyAntipov** [RobLoach/docker-composer#27]
Hello. I'd like propose idea about persistent mode whenever something like gulp will watch that composer config has changed, and composer will re-update vendor components. It's useful for development stage.

**Comment by AndreyAntipov** [comment]
Workaround example with shell script and composer hooks.

composer.json
```json
{
  "scripts":
  {
    "post-install-cmd":
    [
      "/scripts/composer-watch-update.sh _COMPOSER_JSON_CONFIG_PATH_"
    ]
  },
  "config":
  {
    "process-timeout": 0,
  },
```
composer-watch-update.sh
```bash
#!/bin/bash

FILE="$1"
CMD="$2"
DIR=$(dirname "${FILE}")

LAST=`ls -l "$FILE"`
while true; do
  sleep 1
  NEW=`ls -l "$FILE"`
  if [ "$NEW" != "$LAST" ]; then
    cd $DIR
    composer update
    LAST="$NEW"
  fi
done
```

docker-compose.yml
```yml
application:
  image: busybox
  volumes:
    - ./scripts/:/scripts/:ro
    - ./tmp/development/payload/:/app/
    - ./config/development/composer.json:/app/composer.json:ro
  command: "true"
# platform dependency manager
payload:
  image: composer/composer
  mem_limit: 256m
  memswap_limit: 512m
  command: 'install'
  volumes_from:
    - application
```
