### ISSUE TITLE
How could I make composer container execute in a other container?

### ISSUE THREAD

**Issue by meotimdihia** [RobLoach/docker-composer#88]
From https://hub.docker.com/r/composer/composer/

> **akosgluebe** said (3 months ago)
> Hello,
> 
> It is shown how to make an alias: "Now the composer command is available native on host". Great.
> How could I make this alias/this command available in a running container? Lets say I start up, for example, the latest jenkins container (or whatever other container), how could I use this composer inside that container? (I would like to avoid docker in docker)
> Thanks!

i have same his question, can we run this in a other container ? 
i see this problem a long time ago but can't think any simple resolution. 

Anyone may suggest for me, thx :)

**Comment by RobLoach** [comment]
Do you have either a Dockerfile or docker-compose.yml that you could send over to test? The idea is here is that you mount the volumes across the containers, and then run Composer through the Composer container.

**Comment by meotimdihia** [comment]
I am using this `docker-compose.yml`:
```
version: '2'
services:
    php-fpm:
        build:
            context: ./php-fpm
        image: plf_php-fpm:5.6
        links:
            - mysql:mysql
            - redis:redis
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=platform-admin
            - MYSQL_PASSWORD=platform123
            - MYSQL_DATABASE=platform
            - REDIS_HOST=redis            
        depends_on:
            - redis
            - mysql
        volumes:
            - ../src/:/var/www/html/
            - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    nginx:
        image: nginx:1.7.10
        ports:
            - 8080:80
        links:
            - php-fpm:php-fpm
        volumes_from:
            - php-fpm
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
    mysql:
        build:
            context: ./mysql
        image: meotimdihia/plf_mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/import/dump.sql:/tmp/dump.sql
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_USER=platform-admin
            - MYSQL_PASSWORD=platform123
            - MYSQL_DATABASE=platform
    redis:
        image: redis:3-alpine
    jenkins:
        image: jenkins:2.3
        ports:
            - 8060:8080
            - 50000:50000
        volumes:
            - ./jenkins/home:/var/jenkins_home
            - ../src/:/var/www/html/
```

My workflow is like this: Push my code to github repository → Github webhook request to my Jenkins container URL → Jenkins container pull github repository → **run `Composer install` at here** .
But how to execute `composer install` container here ? 
Now i recognize this problem should be at docker groups , LOL.
But if you can suggest me , its a big help.

**Comment by RobLoach** [comment]
1. Add a Composer service, mounting the volumes:

    ``` yaml
    composer:
        image: composer/composer
        volumes_from: php-fpm
        working_dir: /var/www/html
    ```

2. Run Composer through `docker-compose`:

    ```
    docker-compose run composer install
    ```

**Comment by meotimdihia** [comment]
We can run docker-composer on host machine , but i wonder we can execute `composer install` in Jenkins container , because i need to execute automatically `composer install`.

In real my case i am trying to setup on kubernetes (google container engine) and docker-compose on localhost.

**Comment by RobLoach** [comment]
Another solution is to change the [entrypoint](https://docs.docker.com/compose/compose-file/#/entrypoint) and [command](https://docs.docker.com/compose/compose-file/#/command) and make your own script to run Composer install when the service starts.

**Comment by meotimdihia** [comment]
thx for your answer, after some research in docker's documention, i see docker remote API :
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/exec-create
And
kubernetes API : 
http://kubernetes.io/kubernetes/third_party/swagger-ui/#!/api%2Fv1/connectPostNamespacedPodExec

i will try to follow this direction: Jenkin's container will call remote API to execute a command in Composer's container.

I close this issue, thank you once again.

**Comment by delmicio** [comment]
@RobLoach I've been trying the past two days to include auto composer commands in my docker-compose file and failing.
Could you share with us your solution if you have got one.

```
version: "3"

services:
  composer:
    image: composer/composer:php5-alpine
    volumes:
      - ./app/:/app
    command: ["install --ignore-platform-reqs", "dump-autoload --optimize"]
```
