### ISSUE TITLE
Composer not looking at php container requirements

### ISSUE THREAD

**Issue by bobmulder** [RobLoach/docker-composer#92]
I am trying the composer image like this:

```
version: '2'
services:
  php:
    build: .
    volumes:
      - .:/var/www/html
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./server.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  composer:
    image: 'composer/composer'
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: update
```

When running `docker-compose run composer`, I'll get the following message:

> Your requirements could not be resolved to an installable set of packages.

Next a list follows of unresolved requirements because some extensions of the framework are not installed. However, I installed them on my own build, which should be enough.

Any suggestions what I'm doing wrong?

In my opinion the composer image should only install composer and run the commands. Requirements of the machine are done in the php build....
