### ISSUE TITLE
Add docker-compose example to README

### ISSUE THREAD

**Issue by KCErb** [RobLoach/docker-composer#96]
Hi, I'm new to docker-compose and wanted to use this docker container in my project. I'm a little unsure what that would look like. Here's my best guess, can you advise?

```yaml
php:
  build: ./php/
  links:
    - composer
# skipping lines . . .

composer:
  build: ./composer/
# etc...
```

And then inside of `./composer/` a Dockerfile like so

```dockerfile
FROM composer/composer

# Use local composer.json file
COPY ./composer.json /var/www/html/composer.json
WORKDIR /var/www/html
RUN composer install
```

Thanks for the great project(s)!
